### ISSUE TITLE
email r markdown

### ISSUE THREAD

**Issue by 1beb** [joshuaulrich/stl-rug#1]
Hey Josh, 

I was looking throguh your presentation material, with respect to emailing R markdown reports: 

```
## Outcome
- Works in most clients, may have to opt-in for sender or domain
- Images only load if user is online
- E-mail body is small
```

Have you tested it successfully with Gmail or other providers? I've had no luck there. If the report is large it outputs junk to the user.

**Comment by joshuaulrich** [comment]
I've personally never done any of that.  I'll contact the presenter and see if they have an answer.
